version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.6/data

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: "192.168.56.1"
      KAFKA_CREATE_TOPICS: "enseignant-event-topic:1:1"

volumes:
  zookeeper-data: